
from __future__ import annotations
from typing import Protocol, Any, Dict
import pandas as pd

class MarketData(Protocol):
    def get_klines(self, symbol: str, interval: str, limit: int = 1000) -> pd.DataFrame: ...

class Signal(Protocol):
    def decide(self, df: pd.DataFrame, params: Dict[str, Any]) -> Dict[str, Any]: ...

class RiskGate(Protocol):
    def can_open(self, decision: Dict[str, Any]) -> tuple[bool, str]: ...

class Executor(Protocol):
    def place(self, decision: Dict[str, Any]) -> None: ...

class Telemetry(Protocol):
    def snapshot(self, df: pd.DataFrame) -> None: ...
    def decision(self, decision: Dict[str, Any]) -> None: ...
    def health(self, **payload: Any) -> None: ...
